// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWsfcVQNj5G_Sz8DKRAspU5iBY92WoA1c',
    appId: '1:713120615110:web:49e3cdd6f4b01225f2a5c7',
    messagingSenderId: '713120615110',
    projectId: 'fandome-x-5b240',
    authDomain: 'fandome-x-5b240.firebaseapp.com',
    storageBucket: 'fandome-x-5b240.appspot.com',
    measurementId: 'G-TT17Y33PKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXShq8pdZK1pCMhLkNlf-o8lflmy4JgRk',
    appId: '1:713120615110:android:433e2fdce3fff286f2a5c7',
    messagingSenderId: '713120615110',
    projectId: 'fandome-x-5b240',
    storageBucket: 'fandome-x-5b240.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyConuzdWAQbYkWnQCkc9A21eucRwiBk_Sk',
    appId: '1:713120615110:ios:75fc1db573efe2aff2a5c7',
    messagingSenderId: '713120615110',
    projectId: 'fandome-x-5b240',
    storageBucket: 'fandome-x-5b240.appspot.com',
    iosClientId: '713120615110-d9um416ffet1uk8b75q5k9ejr3us8dv9.apps.googleusercontent.com',
    iosBundleId: 'com.example.fandomex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyConuzdWAQbYkWnQCkc9A21eucRwiBk_Sk',
    appId: '1:713120615110:ios:75fc1db573efe2aff2a5c7',
    messagingSenderId: '713120615110',
    projectId: 'fandome-x-5b240',
    storageBucket: 'fandome-x-5b240.appspot.com',
    iosClientId: '713120615110-d9um416ffet1uk8b75q5k9ejr3us8dv9.apps.googleusercontent.com',
    iosBundleId: 'com.example.fandomex',
  );
}
